import { test, expect } from '@playwright/test';
import data from './data.json';

test('submit', async ({ page }) => {
  await page.goto(data.url);
  await page.getByRole('textbox', { name: 'Email' }).click();
  await page.getByRole('textbox', { name: 'Email' }).fill(data.email);
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill(data.password);
  await page.getByRole('checkbox', { name: 'Accept Terms and Conditions.' }).check();
  await page.getByRole('button', { name: 'SIGN IN' }).click();
  await page.getByRole('button', { name: 'Close' }).click();
  await page.getByRole('button', { name: 'Open' }).click();
  await page.getByRole('option', { name: data.account }).click();
  await page.getByRole('button', { name: 'Yes' }).click();
  await page.getByRole('button', { name: 'Create New Application' }).click();
  await page.getByText(data.applicationType).click();
  await page.getByRole('button', { name: 'Create Application' }).click();
  await page.getByRole('button', { name: 'Create New Application' }).press('ControlOrMeta+=');
  await page.locator('.MuiFormControl-root.MuiFormControl-marginDense').first().click();
  await page.getByRole('option', { name: data.licenseNumber }).click();
  await page.getByRole('combobox', { name: 'Update Type' }).click();
  await page.getByRole('option', { name: data.updateType }).click();
  await page.getByRole('textbox', { name: 'Street' }).fill(data.address.street);
  await page.getByRole('textbox', { name: 'Street' }).press('Tab');
  await page.getByRole('textbox', { name: 'Unit No.' }).fill(data.address.unit);
  await page.getByRole('textbox', { name: 'City' }).fill(data.address.city);
  await page.getByRole('textbox', { name: 'City' }).press('Tab');
  await page.getByRole('combobox', { name: 'County' }).click();
  await page.getByRole('option', { name: data.address.county }).click();
  await page.getByRole('combobox', { name: 'State' }).click();
  await page.getByRole('option', { name: data.address.state }).click();
  await page.getByRole('textbox', { name: 'Zip Code' }).click();
  await page.getByRole('textbox', { name: 'Zip Code' }).fill(data.address.zip);
  await page.getByRole('combobox', { name: 'Missouri House of' }).click();
  await page.getByRole('option', { name: data.address.houseDistrict, exact: true }).click();
  await page.getByRole('combobox', { name: 'US Congressional District' }).click();
  await page.getByRole('option', { name: data.address.congressionalDistrict }).click();
  await page.getByRole('textbox', { name: 'Facility GPS Coordinates - Latitude' }).click();
  await page.getByRole('textbox', { name: 'Facility GPS Coordinates - Latitude' }).fill(data.address.latitude);
  await page.getByRole('button', { name: 'Verify Address' }).click();
  await page.getByRole('dialog', { name: 'Address Selection' }).waitFor({ state: 'visible' });
  await page.getByRole('heading', { name: 'Entered Address' }).click();
  await page.getByRole('button', { name: 'Done' }).click();
  await page.getByLabel('Do you attest that the').getByText('Yes').click();
  await page.getByRole('button', { name: 'Verify Address' }).click();
  await page.getByRole('dialog', { name: 'Address Selection' }).waitFor({ state: 'visible' });
  await page.getByRole('heading', { name: 'Entered Address' }).click();
  await page.getByRole('button', { name: 'Done' }).click();
  await page.getByRole('tab', { name: 'Attestations' }).click();
  await page.getByRole('radio', { name: 'Yes' }).check();
  await page.getByRole('textbox', { name: 'Signature', exact: true }).click();
  await page.getByRole('textbox', { name: 'Signature', exact: true }).fill(data.signature);
  await page.getByText('Applications/Partial Business License UpdateFixturesMO-PBLULicense').click();
  await page.getByRole('tab', { name: 'Documents' }).click();
  await page.getByRole('button', { name: 'Auto fill documents' }).click();
  await page.getByRole('button', { name: 'Save & Next' }).click();
  await page.getByRole('button', { name: 'Save & Next' }).click();
  await page.getByRole('tab', { name: 'Review' }).click();
  await page.getByRole('button', { name: 'Submit' }).click();
});
